require_relative '../modules/book'
require_relative '../modules/label'
require_relative '../user_interface/book_ui'
require_relative '../modules/game'
require_relative '../modules/author'
require 'json'
