require_relative '../modules/book'
require_relative '../modules/label'
require_relative '../modules/music_album'
require_relative '../modules/genre'
require_relative '../user_interface/book_ui'
require_relative '../modules/game'
require_relative '../modules/author'
require_relative '../user_interface/music_album_ui'

require 'json'
